### ISSUE TITLE
ODRC: Toevoegen themas

### ISSUE THREAD

**Issue by RutgerICATT** [GeneriekPublicatiePlatformWoo/registratie-component#11]
**Description (why)**
uit PSA: Een beheerder zal in het ODRC thema’s willen kunnen toevoegen, raadplegen, wijzigen en (de)activeren. Thema’s moeten in de data-opslag vastgelegd worden en publicaties moeten hieraan gekoppeld kunnen worden. Deze informatie moet via de API’s ontsloten worden.

**Acceptance criteria (what)**

**Specific details (how)**

**Test plan**

Waardelijst: https://identifier.overheid.nl/tooi/set/scw_toplijst

Note: a theme can be a child of another theme, and the JSON structure above doesn't rule out that a theme is a (direct) child of multiple different other themes

Theme properties:

* `identifier`: URI
* `name`: name of the theme
* `subthema's`: array of nested themes, which may all have their own sub themes (!)
* `publicatieStatus`: actief/niet_actief
* `origin`: enum, `waardelijst` or `zelf_toegevoegd`

**Tasks**

- [x] Define data model for `Thema` and register in the admin. Probably best to use django-treebeard for the tree structure (MPTT)
- [x] Expose via API at `/api/v1/themas`
    - List endpoint is paginated
    - List endpoint has search parameter on `name`
    - List endpoint includes nested themes if relevant, for each item in the list
    - Create/update for origin `zelf_toegevoegd`, waardelijst records may not be mutated
    - publicatieStatus can be updated irrespective of `origin`
    - When creating a theme, you must be able to specify it needs to be a child of another theme (and specify before/after sibling)
- [x] Add management command to populate themes from waardelijst
    - Must produce a fixture, with natural keys
    - Fixture needs to be baked in docker image and automatically loaded on application start (post-migrate signal)

**Comment by MarcoKlerks** [comment]
`publicatieStatus` zou ik er nog even uithouden Ik denk niet dat veel gemeenten dit voor gebruikers willen beperken.

Ook is het voorlopig niet nodig dat deze thema's handmatig uitgebreid kunnen worden, dus het attribuut `origin` kan ook voorlopig weg.

Met "thema's" in het PSA bedoelde ik iets anders dan dat waardenlijstje wat een stel ambtenaren bij het ministerie hebben verzonnen. Ik had voor het PSA een andere term moeten verzinnen, maar dat is wijsheid achteraf.

Deze user story heb ik een lagere prio gegeven, omdat thema's niet verplicht zijn voor de aansluiting op de Woo-index.

**Comment by sergei-maertens** [comment]
@MarcoKlerks the test environment has been updated, details are in Slack :)

**Comment by MarcoKlerks** [comment]
Testresultaten:

1. `publicatiestatus` en `origin` zitten er terecht niet in. Zie vorige opmerking van 10 sept.
2. "List endpoint has search parameter on name" zit er niet in. Voorlopig prima; geen showstopper.
3. Het is wenselijk om alleen de thema's op het hoogste niveau op te kunnen vragen. Dat maakt het mogelijk om in het ODPC of OODBP eerst de hoofdthema's te tonen en daarna, na gebruikersinteractie, de subthema's. Dit criterium had ik nog niet meegegeven, dus hier maak ik een nieuwe user story voor.

Conclusiie: story kan naar Done.
