### ISSUE TITLE
ODRC: Set up foundation for logging/audit trails

### ISSUE THREAD

**Issue by sergei-maertens** [GeneriekPublicatiePlatformWoo/registratie-component#16]
> Als informatiebeveiliger / beheerder wil ik dat wijzigingen gelogd worden, zodat ik later kan reconstrueren wie wanneer wat heeft gedaan met de gegevens (bijvoorbeeld omdat er iets niet klopt).

** Description (why)**

**Acceptance criteria (what)**

- De creatie, mutatie of verwijdering van een data-object wordt gelogd (m.u.v. de log-records zelf)
- Optioneel: de raadpleging van een data-object wordt gelogd. Graag laten weten of dit wordt meegenomen!
- Uit de logging blijkt:
  - welke handeling is uitgevoerd,
  - op welke data-objecten de handeling is uitgevoerd,
  - welke gebruiker de handeling heeft uitgevoerd,
  - wanneer (datum en tijd) de handeling is uitgevoerd,
  - op welke wijze de handeling is uitgevoerd (welk component sprak de API aan?)
  - met welk resultaat (gelukt/mislukt, liefst met meer info, zoals wat gewijzigd is).
- De logging is niet muteerbaar.
- De documentatie is bijgewerkt (Read the Docs)
- Een grafisch datamodel van de database is beschikbaar / bijgewerkt (op GitHub of Read the Docs of elders)

**Specific details (how)**

**Test plan**

**Tasks**

- [x] Add django-timeline-logger dependency
- [x] Set up admin integration for django-timeline-logger so that log records can only be read, even for superusers (proxy model)
- [x] Set up admin-index configuration to put the audit trail in the "Logging" category in admin-index
- [x] Add a `logging` package/module that wraps the ORM actions
- [x] Each log record needs at minimum:
    - User identifier (taken from API call request headers, and/or django admin overrides). These will contain users that don't exist in `accounts.User`!
    - User representation/display name, e.g. the name / initials + last name
    - Reference to the object that was acted upon (use the GFK)
    - Type of action, this *may* be taken from audit trail request headers. E.g. `create`, `update`, `publish`, `unpublish/retract`
    - Any additional metadata relevant to the action being logged
- [x] Ensure that log records can be searched in the admin, based on user (ID + representation), date hierarchy, type of action
- [x] API endpoints must support (and require!) custom request headers for audit trails: Audit-User-Representation, Audit-User-ID, Audit-Remarks. ODPC/ODBP are responsible for populating these.

**Comment by MarcoKlerks** [comment]
@sergei-maertens Ik heb hier net zoals bij #2 ook alvast acceptatie-criteria toegevoegd, omdat deze story randvoorwaardelijk is voor die story.

Ik vermoed dat mijn criteria verschillen van jullie standaard-oplossing. Laat even weten wat de verschillen zijn, dan kan ik daar wat van vinden (= schrappen of aparte story van maken).

Ik wil nog een aparte story maken om de logging in de beheerinterface te tonen.

**Comment by sergei-maertens** [comment]
@MarcoKlerks is het ook voldoende als de logs/audit trails via de beheeromgeving van de registratiecomponent inzichtelijk (en te exporteren zijn) ipv deze ook via de API te onsluiten? Dat is namelijk een stuk minder werk :)

**Comment by sergei-maertens** [comment]
Reference on how we do this in Open Forms: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/logging/logevent.py

I don't want a carbon copy of this, we can definitely improve on this and make a better API (public API defined in `woo_publications.logging.__init__` module so that we can do e.g. `from woo_publications.logging import audit_event`

```py
def audit_event(
    content_object: models.Model,
    user_id: str,
    user_display: str,
    django_user: None | User,
    **whatever_else_is_needed,
) -> None:
```

DRF hooks for extra parameters/request headers: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/api/drf_spectacular/hooks.py

**Comment by MarcoKlerks** [comment]
@sergei-maertens De GitHub-bot heeft de story naar In Progress gezet. Klopt dat? Of moet hij naar Testing?

**Comment by sergei-maertens** [comment]
> [@sergei-maertens](https://github.com/sergei-maertens) De GitHub-bot heeft de story naar In Progress gezet. Klopt dat? Of moet hij naar Testing?

Naar testing inderdaad, maar het was niet verkeerd omdat ik nog een bug aan het fixen was ;) Dus nu staat de echte versie klaar voor testing op de testomgeving!

Daarnaast:

> Optioneel: de raadpleging van een data-object wordt gelogd. Graag laten weten of dit wordt meegenomen!

Dit gebeurt voor: thema's, informatiecategorieën, publicaties, documenten, m.u.z. van de lijstweergaven - die worden niet gelogd.

Andere AC:

> op welke wijze de handeling is uitgevoerd (welk component sprak de API aan?)

Deze hangt wat samen met de API autorisatie. Het valt nu impliciet af te leiden: als er geen _django user_ gekoppeld is, dan is het een actie die niet via de beheerinterface (dus publicatiecomponent) verlopen is.

> met welk resultaat (gelukt/mislukt, liefst met meer info, zoals wat gewijzigd is).

Gelukt/mislukt - als iets niet gelukt is, dan zal het typisch ook niet gelogd zijn omdat er dan een crash is. De informatie daarvan zien we in Sentry (error monitoring) terug. Er is een beetje een uitdaging hier ook - op het moment dat iets fout gaat en een database transactie teruggerold wordt, ben je ook je logs kwijt want die gaan in dezelfde transactie. Mits er tijd en budget is, is het een optie om dat via een andere route in te schieten, maar die heb ik i.v.m. de complexiteit nu buiten scope gelaten.

We loggen nu dus wel een snapshot bij de actie:

* read: referentie naar het gelezen object
* create: referentie naar aangemaakt object, snapshot van de data van het object
* update: referentie naar het bijgewerkte object, snapshot van de nieuwe data van het object
* delete: referentie naar het verwijderde object, snapshot van de data vlak voordat het verwijderd is

Dit gebeurt voor acties uitgevoerd in de beheeromgeving (goed voor demo-doeleinden, bijvoorbeeld een publicatie met een document aanmaken!) en acties via de API uitgevoerd.

**Comment by MarcoKlerks** [comment]
Test-resultaten:

Disclaimers: 
- Ik kon van de API alleen de create-operatie testen, omdat het ODPC de andere acties nog niet aanroept. Ik heb alle acties wel via de beheer-interface kunnen testen.
- Bij de thema's heb ik alleen het raadplegen getest. Crëeren en muteren zijn niet mogelijk. Verwijderen is onwenselijk.
- Documenten heb ik niet getest. Via het ODPC worden deze nog niet aangeleverd. Voor het handmatig toevoegen via het beheer-portaal moet ik handmatig een UUID invoeren. Dat lijkt mij onwenselijk. Daar moet ik nog een user story voor aanmaken.


1. Als ik in de beheer-interface naar een `publicatie` ga en rechtsboven klik op de knop "geschiedenis", dan zie ik alleen de updates, maar niet de creates en reads. Bij de "(audit) log entries" zie ik deze wel.
2. Bij `informatiecategorie` zie ik bij de "geschiedenis" wel de create naast de updates, maar niet de reads. Bij de "(audit) log entries" zie ik deze wel.
3. Bij de "(audit) log entries" zit bovenaan een zoekveldje. Zoeken op termen uit de titel werkt niet. Zoeken op een deel van de gebruikersnaam (bijvoorbeeld "Klerks") werkt wel.
4. Documentatie is niet bijgewerkt (Read the Docs). Die is sowieso nog behoorlijk leeg, dus misschien een andere keer over hebben.
5. Wens: Bij de "geschiedenis" wordt bij een mutatie een hele heldere "actie" omschreven. Kan deze ook getoond worden wanneer een regel in de "(audit) log entries" wordt aangeklikt en geopend?
6. Wens: Kan in de lijst "(audit) log entries" een kolom worden toegevoegd met over wat voor data-object een regel betrekking heeft? Gaat de regel over een `publicatie` of `document` of 'informatieobject` of ...? En kan dit ook als filter toegevoegd worden?

Laat even weten wat nu nog gefixt kan worden en wat vraagt om aparte user stories.

**Comment by sergei-maertens** [comment]
Ik beantwoord even de punten inline!

> Test-resultaten:
> 
> Disclaimers:
> 
> * Ik kon van de API alleen de create-operatie testen, omdat het ODPC de andere acties nog niet aanroept. Ik heb alle acties wel via de beheer-interface kunnen testen.
> * Bij de thema's heb ik alleen het raadplegen getest. Crëeren en muteren zijn niet mogelijk. Verwijderen is onwenselijk.
> * Documenten heb ik niet getest. Via het ODPC worden deze nog niet aangeleverd. Voor het handmatig toevoegen via het beheer-portaal moet ik handmatig een UUID invoeren. Dat lijkt mij onwenselijk. Daar moet ik nog een user story voor aanmaken.

Documenten kunnen inline bij de publicatie of individueel "toegevoegd worden". Er is (nog) geen upload-functionaliteit omdat we #19 in komende sprint oppakken. Ook daar ligt de focus op de API endpoints voor ODPC. Waarschijnlijk best om een expliciete story aan te maken om ook documenten via de ODRC beheerinterface te kunnen uploaden, dat heeft namelijk wel wat voeten in de aarde.


> 1. Als ik in de beheer-interface naar een `publicatie` ga en rechtsboven klik op de knop "geschiedenis", dan zie ik alleen de updates, maar niet de creates en reads. Bij de "(audit) log entries" zie ik deze wel.

Ik snap de verwarring - deze "geschiedenis" knop bevat enkel de operaties via de beheer-interface en komt "gratis" mee met het framework wat we gebruiken. In de lijstweergave staat de link naar de logs horend bij een specifiek object, en dat is wat in deze US gerealiseerd is.

@bart-maykin - kan je `src/woo_publications/metadata/templates/admin/metadata/change_form_object_tools.html` overriden zodat er ook een "View logs" naast "geschiedenis" komt te staan, en hetzelfde voor de `publications` en `accounts` apps. Relevante documentatie: https://docs.djangoproject.com/en/4.2/ref/contrib/admin/#overriding-admin-templates

![image](https://github.com/user-attachments/assets/e6fc36b5-50e6-40b5-8209-88df1f2bd603)

Aparte PR voor dit graag.

> 2. Bij `informatiecategorie` zie ik bij de "geschiedenis" wel de create naast de updates, maar niet de reads. Bij de "(audit) log entries" zie ik deze wel.

Zie 1. - reads ga je hier nooit terugzien, en ook writes via de API ga je hier niet terug zien. We gaan ook deze link/button niet weghalen, want deze geschiedenis van de admin kunnen inzien is nodig om support te kunnen leveren.

> 3. Bij de "(audit) log entries" zit bovenaan een zoekveldje. Zoeken op termen uit de titel werkt niet. Zoeken op een deel van de gebruikersnaam (bijvoorbeeld "Klerks") werkt wel.

Komt door de aarde van loggegevens, een deel is gestructureerde data (type event zoals create/read/update/delete, gebruiker die de actie uitvoerde ), de rest is ongestructureerd want het hangt samen met het type object die gewijzigd is. Hier op een gestructureerde manier doorheen zoeken is lastig omdat het niet op een database-efficiente manier kan.

Wat we wel doen is alvast de weergave van het object cachen op de log record - dit kunnen we doorzoeken. Maar dat betekent dat je bij de wijziging van de titel (als die in die weergave gebruikt wordt) oude/nieuwe records niet gaat terugvinden.

Mijn advies is dan ook om in de lijstweergave van het object zelf te zoeken, en vervolgens de link "Show logs" aan te klikken, want die zijn op basis van database IDs gekoppeld en veel robuuster.

@bart-maykin mogelijks toch `extra_data___cached_object_repr` aan de `search_fields` toevoegen, free win, maar alleen als het niet voor crashes zorgt als een log record helemaal geen `_cached_object_repr` heeft. Aparte PR graag.

> 4. Documentatie is niet bijgewerkt (Read the Docs). Die is sowieso nog behoorlijk leeg, dus misschien een andere keer over hebben.

Mea culpa - al lijkt het me verstandig dat we het eerst zelf eens zien wat de UX moet zijn voor we met screenshots e.d. in de weer gaan, want dat is zonde van de tijd anders.

> 5. Wens: Bij de "geschiedenis" wordt bij een mutatie een hele heldere "actie" omschreven. Kan deze ook getoond worden wanneer een regel in de "(audit) log entries" wordt aangeklikt en geopend?

Aparte userstory en m.i. niet onderdeel van BB MVP - de semantische operatie achterhalen uit een RESTful API-actie is gokwerk. De API header `Audit-Remarks` slaan we op (geven we nog niet weer), maar dat lijkt me de betere plek/manier om dit op te lossen, want de ODPC weet wel wat er gebeurt ("publicatie", "intrekken publicatie"). Het is wel een wat grijs gebied.

> 6. Wens: Kan in de lijst "(audit) log entries" een kolom worden toegevoegd met over wat voor data-object een regel betrekking heeft? Gaat de regel over een `publicatie` of `document` of 'informatieobject` of ...? En kan dit ook als filter toegevoegd worden?

Lijkt me kleine moeite (30min). De filter zal echter veel meer objecttypen tonen dan waarvoor een audit-regels zijn. Dat kunnen we aanpassen, maar dat kost een factor meer tijd (1 dag).

@bart-maykin `content_type` toevoegen aan `list_select_related`, `list_display` en `list_filter`. Behoeft geen extra tests wat mij betreft, we hebben al smoketests voor de lijst/filter functionaliteiten.
 
> Laat even weten wat nu nog gefixt kan worden en wat vraagt om aparte user stories.

Done :-)

**Comment by MarcoKlerks** [comment]
Helaas, ik heb nog een issue gevonden...

Als ik in de beheer-interface een publicatie raadpleeg, dan staan daar (terecht) de documenten bij. Rechtsboven ieder document staat een vinkje 'verwijderen'. Als ik dat aanvink en opsla, dan wordt het document inderdaad verwijderd. Deze verwijdering wordt echter niet gelogd. Wel wordt er een mutatie van de publicatie gelogd.

Óf deze wijze van verwijderen wordt ook gelogd óf het vinkje wordt weggehaald.
