### ISSUE TITLE
ODCR: set up API keys and API Authn/Authz model

### ISSUE THREAD

**Issue by sergei-maertens** [GeneriekPublicatiePlatformWoo/registratie-component#17]
The publication component and citizen portal will consume the registration API. For this, they need to authenticate using an API key.

**Tasks**

- ~~Define two roles: `publication_component`, `citizen_portal`~~ SCRAPPED
    - publication component implies read + write of all data
    - citizen portal implies read of published (!) data only
- [x] Define data model + set up admin for API Key, similar to objects API
    - API key, (securily) randomly generated string
    - Contact person name, phone + email address (optional fields)
    - Roles to apply, which is one or more of the two roles above (simple `ArrayField` should suffice)
- [x] Define DRF authentication class
    - Authenticate based on the API key in the request header `Authorization: Token <key>`
    - This is the only allowed authentication class (so don't expose/enable BasicAuth, TokenAuth, SessionAuth...)
    - Must be properly documented in the generated API schema
- [x] Define permission classes for read/write permissions, which are inferred/taken from the roles associated with the API key

**Comment by MarcoKlerks** [comment]
Geen acceptatie criteria gedefinieerd. Dit is te technisch voor mij om daar meer zinnigs over te zeggen dan de gebruikelijke open deuren.

**Comment by sergei-maertens** [comment]
For now put this behind a feature flag (envvar) `ENABLE_API_AUTH`, default enabled.

**Comment by mstokericatt** [comment]
Na implementatie kan "ODPC: calls naar het ODRC authentiseren" #66 gerealiseerd worden.

**Comment by MarcoKlerks** [comment]
De hashtag-link in de vorige mention verwees niet naar de juiste story, want andere repository. De juiste link is [ODPC #66](https://github.com/GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component/issues/66).

**Comment by sergei-maertens** [comment]
Needs to be tested on our deployed instance, and for that it needs to be deployed first :)

**Comment by MarcoKlerks** [comment]
Ik kan dit niet functioneel testen. @felixcicatt , kun jij hier even naar kijken?
