### ISSUE TITLE
ODRC: Add filter parameters to Publicatie list endpoint

### ISSUE THREAD

**Issue by sergei-maertens** [GeneriekPublicatiePlatformWoo/registratie-component#68]
### Thema / Theme

API

### Omschrijving / Description

GeneriekPublicatiePlatformWoo/Openbaar-Documenten-Publicatie-Component#8 exposes some filtering/ordering capabilities, which must be supported by the backend:

- (partial) search through the `officieleTitel` field
- (partial) search through the `verkorteTitel` field
- filter on publication registration date

**Tasks**

Filters apply to the `documenten` API endpoint (list) as this will be used for the sitemap generation

- [x] Implement a `search` filter parameter, which searches through `officiele_titel` and `verkorte_titel` (`icontains`)
- [x] Implement the filter parameters `registratiedatum__lte` and `registratiedatum__gte` to filter on a range of when publications were created
- [x] Filter on information category/categories (this must follow the `publicatie` FK to perform the filter)

### Toegevoegde waarde / Added value

Support necessary UI actions.

### Aanvullende opmerkingen / Additional context

Another US will be needed to filter (based on the audit trails) only publications created by the authenticated user.

**Comment by sergei-maertens** [comment]
@MarcoKlerks you can add some acceptance criteria if you feel that it's needed, but IMO this is ready to pick up for development
